language: c
os:
  - linux
  - osx
env:
  - LIBWEBSOCKETS_VERSION=1.7.9
  - LIBWEBSOCKETS_VERSION=2.0.3
  - LIBWEBSOCKETS_VERSION=2.1.1
  - LIBWEBSOCKETS_VERSION=2.2.1
sudo: required
dist: trusty
branches:
  only:
    - master
addons:
  apt:
    packages:
      - cmake
      - libjson-c-dev
      - libssl-dev
install: |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew install cmake openssl json-c
    export CMAKE_OPTIONS="-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl"
  fi
  echo "Compiling libwebsockets-$LIBWEBSOCKETS_VERSION from source..."
  pushd /tmp
    curl -sLo- https://github.com/warmcat/libwebsockets/archive/v$LIBWEBSOCKETS_VERSION.tar.gz | tar xz
    cd libwebsockets-$LIBWEBSOCKETS_VERSION
    cmake $CMAKE_OPTIONS .
    make && sudo make install
  popd
script:
  - mkdir build && cd build
  - cmake $CMAKE_OPTIONS ..
  - make && sudo make install
  - ttyd -v
